---
After:
  - framework/*
  - cms/*
---
StaticExporter:
  extensions:
    - DocumentationStaticPublisherExtension
  disable_sitetree_export: true
Controller:
  extensions:
    - ControllerExtension
Director:
  rules:
    'en//QuickFeedbackForm': 'DocumentationViewer'
QuickFeedbackExtension:
  redirect_field: true
  rate_limit: 1